target_sources(egt PUBLIC FILE_SET HEADERS FILES
    ${CMAKE_SOURCE_DIR}/include/egt/asio.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_signal_set.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/buffer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/net.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/netfwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/internet.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/io_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ts/socket.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/yield.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/datagram_protocol.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/raw_protocol.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/detail/impl/endpoint.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/detail/endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/seq_packet_protocol.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/stream_protocol.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/generic/basic_endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/socket_acceptor_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/dispatch.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/handler_type.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/associated_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/write_at.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_streambuf.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_seq_packet_socket.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/io_service_strand.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/array_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_wait_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_operation.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/scoped_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_recvfrom_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_signal_blocker.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/regex_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/throw_exception.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/strand_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/cstdint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_recv_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/op_queue.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/gcc_hppa_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/scheduler_operation.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/push_options.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/completion_handler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/handler_invoke_helpers.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_socket_connect_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/timer_queue_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_recvmsg_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_event.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/timer_scheduler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/functional.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_signal_blocker.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_fd_set_adapter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_handle_write_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/handler_type_requirements.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/timer_queue_ptime.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/static_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/keyword_tss_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_send_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/socket_ops.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/resolve_query_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/thread_group.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_connect_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/std_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_overlapped_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_wait_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_global.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_async_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_handle_read_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_resolver_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_tss_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/service_registry.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_static_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/descriptor_read_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/variadic_templates.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/object_pool.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/base_from_completion_cond.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/executor_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/socket_types.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/timer_scheduler_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/chrono_time_traits.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/config.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/wrapped_handler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winsock_init.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/scheduler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/resolver_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/consuming_buffers.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_serial_port_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_recvmsg_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/socket_option.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactor_op_queue.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/wait_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/local_free_on_block_exit.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/old_win_sdk_compat.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_socket_send_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_io_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/pipe_select_interrupter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_resolve_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_fd_set_adapter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/signal_blocker.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/throw_error.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/gcc_x86_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_descriptor_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/type_traits.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_overlapped_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/macos_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/conditionally_enabled_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/buffer_resize_guard.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/wince_thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_async_manager.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_service_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_accept_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/buffer_sequence_adapter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/thread_info_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/atomic_count.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_accept_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/call_stack.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/gcc_sync_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/reactive_descriptor_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_iocp_socket_service_base.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/strand_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/winrt_timer_scheduler.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/strand_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/signal_set_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/strand_executor_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/timer_queue_ptime.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/socket_select_interrupter.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_tss_ptr.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/service_registry.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/kqueue_reactor.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/winsock_init.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_static_mutex.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_iocp_io_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/handler_tracking.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/posix_event.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/dev_poll_reactor.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/epoll_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/select_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/timer_queue_set.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/reactive_serial_port_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/strand_executor_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/service_registry.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/dev_poll_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/posix_thread.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/resolver_service_base.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/eventfd_select_interrupter.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/throw_error.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/posix_tss_ptr.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_object_handle_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/scheduler.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/winrt_ssocket_service_base.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/descriptor_ops.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_iocp_handle_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/socket_ops.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/kqueue_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/posix_mutex.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/reactive_socket_service_base.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/buffer_sequence_adapter.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_event.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_iocp_serial_port_service.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/epoll_reactor.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/null_event.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_iocp_io_context.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/winrt_timer_scheduler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/pipe_select_interrupter.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_thread.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/select_reactor.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/impl/win_mutex.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/epoll_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/operation.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/select_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/event.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_event.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/array.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/std_event.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/date_time_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/timer_queue_set.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/handler_work.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/assert.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_connect_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/strand_executor_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_sendto_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_recvfrom_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/eventfd_select_interrupter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_tss_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/scoped_lock.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/recycling_allocator.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/dev_poll_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/conditionally_enabled_event.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/cstddef.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_serial_port_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/signal_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_socket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/hash_map.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winapp_thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_static_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_socket_recv_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_tss_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/resolver_service_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/thread_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_thread_info.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_ssocket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/io_control.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/handler_tracking.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/wait_handler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/gcc_arm_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/timer_queue.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/memory.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_send_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_object_handle_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_handle_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/is_buffer_sequence.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_service_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/limits.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/solaris_fenced_block.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/signal_set_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/std_thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/global.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_global.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/select_interrupter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/resolve_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactor_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/kqueue_reactor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_event.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/descriptor_ops.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/std_global.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/dependent_type.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/std_static_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/descriptor_write_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/is_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/string_view.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_null_buffers_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/socket_holder.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_utils.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/posix_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/deadline_timer_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/pop_options.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_socket_recv_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/buffered_stream_storage.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/std_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/handler_cont_helpers.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/signal_handler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/work_dispatcher.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/handler_alloc_helpers.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/tss_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_timer_scheduler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_static_mutex.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/signal_init.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/concurrency_hint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/fd_set_adapter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/winrt_ssocket_service_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/chrono.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/bind_handler.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/noncopyable.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/socket_select_interrupter.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactive_socket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/resolve_endpoint_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/reactor_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/null_global.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/win_iocp_null_buffers_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/detail/scheduler_thread_info.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/system_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/system_error.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/is_read_buffered.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_socket.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffered_read_stream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/is_write_buffered.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/system_timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/streambuf.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_waitable_timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/write.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_raw_socket.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/error.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/unyield.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffered_stream_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffered_write_stream_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffered_read_stream_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/stream_socket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_io_object.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffered_write_stream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/use_future.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_serial_port.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/handler_continuation_hook.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental/redirect_error.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental/impl/redirect_error.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental/impl/co_spawn.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental/impl/detached.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental/co_spawn.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/experimental/detached.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/read_until.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/dispatch.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/write_at.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/system_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/system_context.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/buffered_read_stream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/handler_alloc_hook.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/write.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/buffered_write_stream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/use_future.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/error_code.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/execution_context.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/read_until.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/read.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/serial_port_base.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/execution_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/serial_port_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/connect.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/thread_pool.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/system_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/src.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/io_context.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/defer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/error.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/executor.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/thread_pool.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/spawn.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/io_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/post.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/impl/read_at.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/read.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/posix/basic_stream_descriptor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/posix/stream_descriptor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/posix/descriptor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/posix/stream_descriptor_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/posix/basic_descriptor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/posix/descriptor_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/serial_port_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/uses_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/wait_traits.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/packaged_task.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/strand.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/execution_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/serial_port_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_datagram_socket.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/placeholders.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/waitable_timer_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/serial_port.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/executor_work_guard.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/connect.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/system_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/raw_socket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/thread.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/basic_resolver_iterator.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address_v6_iterator.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address_v4_iterator.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/detail/socket_option.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/detail/impl/endpoint.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/detail/endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/network_v6.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address_v4.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/udp.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/v6_only.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/tcp.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/bad_address_cast.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/multicast.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/resolver_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/network_v4.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/host_name.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address_v6.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address_v4_range.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/basic_resolver_entry.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/address_v6_range.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/basic_resolver.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/network_v6.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/network_v6.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/address_v6.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/address_v4.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/address.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/host_name.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/address_v4.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/network_v4.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/address.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/address_v6.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/network_v4.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/impl/basic_endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/resolver_query_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/unicast.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/basic_resolver_query.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/resolver_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/icmp.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/basic_endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ip/basic_resolver_results.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffers_iterator.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_socket_iostream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/buffered_stream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_streambuf_fwd.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/time_traits.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/socket_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/coroutine.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/signal_set_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/defer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/steady_timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/version.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_socket_acceptor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/handler_alloc_hook.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/io_context_strand.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/io_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/associated_allocator.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/local/datagram_protocol.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/local/detail/impl/endpoint.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/local/detail/endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/local/connect_pair.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/local/stream_protocol.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/local/basic_endpoint.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/is_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/async_result.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/password_callback.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/engine.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/write_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/buffered_handshake_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/impl/engine.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/impl/openssl_init.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/read_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/stream_core.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/openssl_init.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/openssl_types.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/io.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/verify_callback.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/shutdown_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/detail/handshake_op.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/context_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/stream_base.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/error.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/stream.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/verify_mode.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/impl/rfc2818_verification.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/impl/src.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/impl/error.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/impl/context.ipp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/impl/context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/verify_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/ssl/rfc2818_verification.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/handler_invoke_hook.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/thread_pool.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/signal_set.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/deadline_timer_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/seq_packet_socket_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/spawn.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/io_context.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/error_code.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/post.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/basic_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/random_access_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/overlapped_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/overlapped_ptr.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/basic_random_access_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/object_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/basic_stream_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/basic_object_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/random_access_handle_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/object_handle_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/stream_handle_service.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/windows/stream_handle.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/high_resolution_timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/completion_condition.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_deadline_timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_socket_streambuf.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/basic_stream_socket.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/deadline_timer.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/bind_executor.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/read_at.hpp
    ${CMAKE_SOURCE_DIR}/include/egt/asio/datagram_socket_service.hpp
)
